In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("homicide-data.csv", encoding='iso-8859-1')

In [3]:
df.head(4)

uid  reported_date  victim_last victim_first victim_race victim_age  \
0  Alb-000001       20100504       GARCIA         JUAN    Hispanic         78   
1  Alb-000002       20100216      MONTOYA      CAMERON    Hispanic         17   
2  Alb-000003       20100601  SATTERFIELD      VIVIANA       White         15   
3  Alb-000004       20100101     MENDIOLA       CARLOS    Hispanic         32   

  victim_sex         city state        lat         lon            disposition  
0       Male  Albuquerque    NM  35.095788 -106.538555  Closed without arrest  
1       Male  Albuquerque    NM  35.056810 -106.715321       Closed by arrest  
2     Female  Albuquerque    NM  35.086092 -106.695568  Closed without arrest  
3       Male  Albuquerque    NM  35.078493 -106.556094       Closed by arrest

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52179 entries, 0 to 52178
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   uid            52179 non-null  object 
 1   reported_date  52179 non-null  int64  
 2   victim_last    52178 non-null  object 
 3   victim_first   52179 non-null  object 
 4   victim_race    52179 non-null  object 
 5   victim_age     52179 non-null  object 
 6   victim_sex     52179 non-null  object 
 7   city           52179 non-null  object 
 8   state          52179 non-null  object 
 9   lat            52119 non-null  float64
 10  lon            52119 non-null  float64
 11  disposition    52179 non-null  object 
dtypes: float64(2), int64(1), object(9)
memory usage: 4.8+ MB


In [5]:
df.isnull().sum()

uid               0
reported_date     0
victim_last       1
victim_first      0
victim_race       0
victim_age        0
victim_sex        0
city              0
state             0
lat              60
lon              60
disposition       0
dtype: int64

In [6]:
df=df.dropna()

In [7]:
df.isnull().sum()

uid              0
reported_date    0
victim_last      0
victim_first     0
victim_race      0
victim_age       0
victim_sex       0
city             0
state            0
lat              0
lon              0
disposition      0
dtype: int64

In [8]:
df['disposition'].value_counts()

Closed by arrest         25647
Open/No arrest           23556
Closed without arrest     2915
Name: disposition, dtype: int64

In [9]:
df.drop(columns = 'uid' , inplace = True)

In [10]:
df.drop(columns = 'victim_last' , inplace = True)
df.drop(columns = 'victim_first' , inplace = True)
df.drop(columns = 'state' , inplace = True)

In [11]:
df.head(5)

reported_date victim_race victim_age victim_sex         city        lat  \
0       20100504    Hispanic         78       Male  Albuquerque  35.095788   
1       20100216    Hispanic         17       Male  Albuquerque  35.056810   
2       20100601       White         15     Female  Albuquerque  35.086092   
3       20100101    Hispanic         32       Male  Albuquerque  35.078493   
4       20100102       White         72     Female  Albuquerque  35.130357   

          lon            disposition  
0 -106.538555  Closed without arrest  
1 -106.715321       Closed by arrest  
2 -106.695568  Closed without arrest  
3 -106.556094       Closed by arrest  
4 -106.580986  Closed without arrest

In [12]:
df.drop(columns = 'reported_date' , inplace = True)
df.drop(columns = 'city' , inplace = True)

In [13]:
df.head(5)

victim_race victim_age victim_sex        lat         lon  \
0    Hispanic         78       Male  35.095788 -106.538555   
1    Hispanic         17       Male  35.056810 -106.715321   
2       White         15     Female  35.086092 -106.695568   
3    Hispanic         32       Male  35.078493 -106.556094   
4       White         72     Female  35.130357 -106.580986   

             disposition  
0  Closed without arrest  
1       Closed by arrest  
2  Closed without arrest  
3       Closed by arrest  
4  Closed without arrest

In [14]:
status_mapping = {
    'Closed by arrest': 0,
    'Open/No arrest': 1,
    'Closed without arrest': 2
}

df['disposition_int'] = df['disposition'].map(status_mapping)


In [15]:
df['victim_sex'].value_counts()

Male       40696
Female      7192
Unknown     4230
Name: victim_sex, dtype: int64

In [16]:
status_mapping_sex = {
    'Female': 0,
    'Male': 1,
    'Unknown': 2
}

df['Victim_Sex_int'] = df['victim_sex'].map(status_mapping_sex)

In [17]:
df['victim_race'].value_counts()

Black       33332
Hispanic     6888
White        6319
Unknown      4198
Other         698
Asian         683
Name: victim_race, dtype: int64

In [18]:
status_mapping_race = {
    'Black': 0,
    'Hispanic': 1,
    'White': 2,
    'Unknown' : 3,
    'Other' : 4,
    'Asian' :5
}

df['Victim_Race_int'] = df['victim_race'].map(status_mapping_race)

In [19]:
df.head(10)

victim_race victim_age victim_sex        lat         lon  \
0    Hispanic         78       Male  35.095788 -106.538555   
1    Hispanic         17       Male  35.056810 -106.715321   
2       White         15     Female  35.086092 -106.695568   
3    Hispanic         32       Male  35.078493 -106.556094   
4       White         72     Female  35.130357 -106.580986   
5       White         91     Female  35.151110 -106.537797   
6    Hispanic         52       Male  35.111785 -106.712614   
7    Hispanic         52     Female  35.111785 -106.712614   
8       White         56       Male  35.075380 -106.553458   
9    Hispanic         43       Male  35.065930 -106.572288   

             disposition  disposition_int  Victim_Sex_int  Victim_Race_int  
0  Closed without arrest                2               1                1  
1       Closed by arrest                0               1                1  
2  Closed without arrest                2               0                2  
3       Closed by arrest                0               1                1  
4  Closed without arrest                2               0                2  
5         Open/No arrest                1               0                2  
6       Closed by arrest                0               1                1  
7       Closed by arrest                0               0                1  
8         Open/No arrest                1               1                2  
9         Open/No arrest                1               1                1

In [20]:
df.drop(columns = 'victim_race' , inplace = True)
df.drop(columns = 'victim_sex' , inplace = True)
df.drop(columns = 'disposition' , inplace = True)

In [21]:
df.head(10)

victim_age        lat         lon  disposition_int  Victim_Sex_int  \
0         78  35.095788 -106.538555                2               1   
1         17  35.056810 -106.715321                0               1   
2         15  35.086092 -106.695568                2               0   
3         32  35.078493 -106.556094                0               1   
4         72  35.130357 -106.580986                2               0   
5         91  35.151110 -106.537797                1               0   
6         52  35.111785 -106.712614                0               1   
7         52  35.111785 -106.712614                0               0   
8         56  35.075380 -106.553458                1               1   
9         43  35.065930 -106.572288                1               1   

   Victim_Race_int  
0                1  
1                1  
2                2  
3                1  
4                2  
5                2  
6                1  
7                1  
8                2  
9                1

In [22]:
df.sample(10)

victim_age        lat         lon  disposition_int  Victim_Sex_int  \
34298         26  43.074233  -87.926959                1               1   
8173          21  41.713427  -87.632307                1               1   
49208         35  38.658420  -90.215708                1               1   
49284         30  38.665660  -90.276412                1               1   
20605         29  29.725355  -95.540626                0               1   
21093         29  29.697615  -95.268116                0               1   
25733         35  39.072030  -94.512013                1               2   
49658         26  38.001967 -121.299161                1               1   
1989          33  39.340756  -76.674224                1               1   
19893         23  36.786521 -119.835435                1               1   

       Victim_Race_int  
34298                0  
8173                 0  
49208                0  
49284                0  
20605                0  
21093                1  
25733                3  
49658                2  
1989                 0  
19893                0

In [23]:
df['victim_age'].value_counts()

Unknown    2997
22         2115
21         2091
23         2058
24         1994
           ... 
97            3
96            2
101           1
99            1
102           1
Name: victim_age, Length: 102, dtype: int64

In [24]:
df.replace('Unknown', 0, inplace=True)

In [25]:
df['victim_age'].value_counts()

0      2997
22     2115
21     2091
23     2058
24     1994
       ... 
97        3
96        2
101       1
99        1
102       1
Name: victim_age, Length: 102, dtype: int64

In [27]:
X = df.drop('disposition_int', axis=1)
y = df['disposition_int']

In [28]:
X

victim_age        lat         lon  Victim_Sex_int  Victim_Race_int
0             78  35.095788 -106.538555               1                1
1             17  35.056810 -106.715321               1                1
2             15  35.086092 -106.695568               0                2
3             32  35.078493 -106.556094               1                1
4             72  35.130357 -106.580986               0                2
...          ...        ...         ...             ...              ...
52174         29  38.828704  -77.002075               1                0
52175         19  38.822852  -77.001725               1                0
52176         23  38.828025  -77.002511               1                0
52177         24  38.820476  -77.008640               1                0
52178         17  38.866689  -76.982409               1                0

[52118 rows x 5 columns]

In [29]:
y

0        2
1        0
2        2
3        0
4        2
        ..
52174    0
52175    1
52176    1
52177    1
52178    0
Name: disposition_int, Length: 52118, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
model = LinearRegression()
model.fit(X_train, y_train)
# Make predictions on the test data
y_pred = model.predict(X_test)
# Calculate the R-squared score
r_squared = r2_score(y_test, y_pred)
print(f'R-squared Score: {r_squared}')
print(y_pred[:5])
print(y_test[:5])

R-squared Score: 0.0054154669927316545
[0.59562583 0.59013659 0.54494642 0.54990784 0.59491285]
10681    1
50889    1
16063    0
46663    1
16736    0
Name: disposition_int, dtype: int64


C:\Users\User\AppData\Local\Temp\ipykernel_12028\61390416.py:9: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(y_test[:5])


In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression(random_state=42)

# Fit the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy score
print("Accuracy:", accuracy)
print(y_pred[:5])
print(y_test[:5])

Accuracy: 0.5267651573292402
[1 1 0 0 1]
10681    1
50889    1
16063    0
46663    1
16736    0
Name: disposition_int, dtype: int64


c:\users\user\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Local\Temp\ipykernel_12028\3145800581.py:17: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(y_test[:5])


In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy score
print("Accuracy:", accuracy)
print(y_pred[:5])
print(y_test[:5])

Accuracy: 0.5685917114351496
[1 1 1 1 1]
10681    1
50889    1
16063    0
46663    1
16736    0
Name: disposition_int, dtype: int64


C:\Users\User\AppData\Local\Temp\ipykernel_12028\1991209097.py:17: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(y_test[:5])


In [41]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn_classifier = KNeighborsClassifier(n_neighbors=3)

# Fit the classifier to the training data
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn_classifier.predict(X_test)

# Calculate and print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print(y_pred[:5])
print(y_test[:5])

Accuracy: 0.5352072141212586
[1 2 0 1 1]
10681    1
50889    1
16063    0
46663    1
16736    0
Name: disposition_int, dtype: int64


C:\Users\User\AppData\Local\Temp\ipykernel_12028\1158008877.py:16: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(y_test[:5])


In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf = DecisionTreeClassifier(random_state=42)

# Fit the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(y_pred[:5])
print(y_test[:5])

Accuracy: 0.5172678434382195
[0 1 1 0 0]
10681    1
50889    1
16063    0
46663    1
16736    0
Name: disposition_int, dtype: int64


C:\Users\User\AppData\Local\Temp\ipykernel_12028\1667115329.py:15: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(y_test[:5])


In [46]:
from sklearn.datasets import make_regression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [47]:
regressor = DecisionTreeRegressor(random_state=42)

# Fit the model on the training data
regressor.fit(X_train, y_train)

# Make predictions on the test data
y_pred = regressor.predict(X_test)

# Calculate the R-squared score
r_squared = r2_score(y_test, y_pred)

print(f"R-squared score: {r_squared}")
print(y_pred[:5])
print(y_test[:5])

R-squared score: -0.7779091951952641
[1. 1. 0. 1. 0.]
10681    1
50889    1
16063    0
46663    1
16736    0
Name: disposition_int, dtype: int64


C:\Users\User\AppData\Local\Temp\ipykernel_12028\188920274.py:14: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(y_test[:5])
